
//人员信息表，记录人员信息
CREATE TABLE `info_staff` (
  `sid` int(11) NOT NULL auto_increment,
  `id_num` varchar(20) NOT NULL,
  `pwd` varchar(100) NOT NULL,
  `staff_name` varchar(10) NOT NULL,
  `staff_type` varchar(10) NOT NULL,
  `department` varchar(20) NOT NULL,
  `mobile` varchar(11) default '',
  `is_admin` tinyint(1) default NULL,
  `is_work` tinyint(1) default NULL,
  `spare1` varchar(20) default NULL,
  `spare2` varchar(20) default NULL,
  PRIMARY KEY  (`sid`,`id_num`),
  UNIQUE KEY `id_num` (`id_num`)
) ENGINE=InnoDB AUTO_INCREMENT=2993 DEFAULT CHARSET=utf8

//记录普通工资单表头结构
CREATE TABLE `m_template` (
  `tid` int(11) NOT NULL auto_increment,
  `month` varchar(6) NOT NULL,
  `param` varchar(20) NOT NULL,
  `value` varchar(200) NOT NULL,
  `valid_tag` tinyint(1) default NULL,
  `remark` varchar(10) default NULL,
  `spare1` varchar(20) default NULL,
  `spare2` varchar(20) default NULL,
  PRIMARY KEY  (`tid`)
) ENGINE=InnoDB AUTO_INCREMENT=28636 DEFAULT CHARSET=utf8


//记录普通工资单数据
CREATE TABLE `data_salary` (
  `salary_id` int(11) NOT NULL auto_increment,
  `month` varchar(6) character set utf8 NOT NULL,
  `department` varchar(30) character set utf8 NOT NULL,
  `id_num` varchar(20) character set utf8 NOT NULL,
  `staff_name` varchar(10) character set utf8 NOT NULL,
  `BONUS_RATE` varchar(6) character set utf8 NOT NULL,
  `expend1` varchar(12) character set utf8 default NULL,
  `expend2` varchar(12) character set utf8 default NULL,
  `expend3` varchar(12) character set utf8 default NULL,
  `expend4` varchar(12) character set utf8 default NULL,
  `expend5` varchar(12) character set utf8 default NULL,
  `expend6` varchar(12) character set utf8 default NULL,
  `expend7` varchar(12) character set utf8 default NULL,
  `expend8` varchar(12) character set utf8 default NULL,
  `expend9` varchar(12) character set utf8 default NULL,
  `expend10` varchar(12) character set utf8 default NULL,
  `expend11` varchar(12) character set utf8 default NULL,
  `expend12` varchar(12) character set utf8 default NULL,
  `expend13` varchar(12) character set utf8 default NULL,
  `expend14` varchar(12) character set utf8 default NULL,
  `expend15` varchar(12) character set utf8 default NULL,
  `expend16` varchar(12) character set utf8 default NULL,
  `expend17` varchar(12) character set utf8 default NULL,
  `expend18` varchar(12) character set utf8 default NULL,
  `expend19` varchar(12) character set utf8 default NULL,
  `expend20` varchar(12) character set utf8 default NULL,
  `itemvalue1` varchar(12) character set utf8 default NULL,
  `itemvalue2` varchar(12) character set utf8 default NULL,
  `itemvalue3` varchar(12) character set utf8 default NULL,
  `itemvalue4` varchar(12) character set utf8 default NULL,
  `itemvalue5` varchar(12) character set utf8 default NULL,
  `itemvalue6` varchar(12) character set utf8 default NULL,
  `itemvalue7` varchar(12) character set utf8 default NULL,
  `itemvalue8` varchar(12) character set utf8 default NULL,
  `itemvalue9` varchar(12) character set utf8 default NULL,
  `itemvalue10` varchar(12) character set utf8 default NULL,
  `itemvalue11` varchar(12) character set utf8 default NULL,
  `itemvalue12` varchar(12) character set utf8 default NULL,
  `itemvalue13` varchar(12) character set utf8 default NULL,
  `itemvalue14` varchar(12) character set utf8 default NULL,
  `itemvalue15` varchar(12) character set utf8 default NULL,
  `itemvalue16` varchar(12) character set utf8 default NULL,
  `itemvalue17` varchar(12) character set utf8 default NULL,
  `itemvalue18` varchar(12) character set utf8 default NULL,
  `itemvalue19` varchar(12) character set utf8 default NULL,
  `itemvalue20` varchar(12) character set utf8 default NULL,
  `itemvalue21` varchar(12) character set utf8 default NULL,
  `itemvalue22` varchar(12) character set utf8 default NULL,
  `itemvalue23` varchar(12) character set utf8 default NULL,
  `itemvalue24` varchar(12) character set utf8 default NULL,
  `itemvalue25` varchar(12) character set utf8 default NULL,
  `itemvalue26` varchar(12) character set utf8 default NULL,
  `itemvalue27` varchar(12) character set utf8 default NULL,
  `itemvalue28` varchar(12) character set utf8 default NULL,
  `itemvalue29` varchar(12) character set utf8 default NULL,
  `itemvalue30` varchar(12) character set utf8 default NULL,
  `itemvalue31` varchar(12) character set utf8 default NULL,
  `itemvalue32` varchar(12) character set utf8 default NULL,
  `itemvalue33` varchar(12) character set utf8 default NULL,
  `itemvalue34` varchar(12) character set utf8 default NULL,
  `itemvalue35` varchar(12) character set utf8 default NULL,
  `itemvalue36` varchar(12) character set utf8 default NULL,
  `itemvalue37` varchar(12) character set utf8 default NULL,
  `itemvalue38` varchar(12) character set utf8 default NULL,
  `itemvalue39` varchar(12) character set utf8 default NULL,
  `itemvalue40` varchar(12) character set utf8 default NULL,
  `itemvalue41` varchar(12) character set utf8 default NULL,
  `itemvalue42` varchar(12) character set utf8 default NULL,
  `itemvalue43` varchar(12) character set utf8 default NULL,
  `itemvalue44` varchar(12) character set utf8 default NULL,
  `itemvalue45` varchar(12) character set utf8 default NULL,
  `itemvalue46` varchar(12) character set utf8 default NULL,
  `itemvalue47` varchar(12) character set utf8 default NULL,
  `itemvalue48` varchar(12) character set utf8 default NULL,
  `itemvalue49` varchar(12) character set utf8 default NULL,
  `itemvalue50` varchar(12) character set utf8 default NULL,
  `itemvalue51` varchar(12) character set utf8 default NULL,
  `itemvalue52` varchar(12) character set utf8 default NULL,
  `itemvalue53` varchar(12) character set utf8 default NULL,
  `itemvalue54` varchar(12) character set utf8 default NULL,
  `itemvalue55` varchar(12) character set utf8 default NULL,
  `itemvalue56` varchar(12) character set utf8 default NULL,
  `itemvalue57` varchar(12) character set utf8 default NULL,
  `itemvalue58` varchar(12) character set utf8 default NULL,
  `itemvalue59` varchar(12) character set utf8 default NULL,
  `itemvalue60` varchar(12) character set utf8 default NULL,
  `welfare1` varchar(12) character set utf8 default NULL,
  `welfare2` varchar(12) character set utf8 default NULL,
  `welfare3` varchar(12) character set utf8 default NULL,
  `welfare4` varchar(12) character set utf8 default NULL,
  `welfare5` varchar(12) character set utf8 default NULL,
  `welfare6` varchar(12) character set utf8 default NULL,
  `welfare7` varchar(12) character set utf8 default NULL,
  `welfare8` varchar(12) character set utf8 default NULL,
  `welfare9` varchar(12) character set utf8 default NULL,
  `welfare10` varchar(12) character set utf8 default NULL,
  `TOTAL_RECEIVABLE` varchar(12) character set utf8 default NULL,
  `deduct1` varchar(12) character set utf8 default NULL,
  `deduct2` varchar(12) character set utf8 default NULL,
  `deduct3` varchar(12) character set utf8 default NULL,
  `deduct4` varchar(12) character set utf8 default NULL,
  `deduct5` varchar(12) character set utf8 default NULL,
  `deduct6` varchar(12) character set utf8 default NULL,
  `deduct7` varchar(12) character set utf8 default NULL,
  `deduct8` varchar(12) character set utf8 default NULL,
  `deduct9` varchar(12) character set utf8 default NULL,
  `deduct10` varchar(12) character set utf8 default NULL,
  `TOTAL_DEDUCT` varchar(12) character set utf8 default NULL,
  `REPAY_AFTER_TAX` varchar(12) character set utf8 default NULL,
  `home_pay` varchar(12) character set utf8 default NULL,
  `DIFFERENCE_EXPLAIN` varchar(200) character set utf8 default NULL,
  `spare1` varchar(30) character set utf8 default NULL,
  `spare2` varchar(20) character set utf8 default NULL,
  `spare3` varchar(20) character set utf8 default NULL,
  PRIMARY KEY  (`salary_id`)
) ENGINE=InnoDB AUTO_INCREMENT=203495 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT

//记录人员登录、查看工资操作记录
CREATE TABLE `log_action` (
  `log_id` int(11) NOT NULL auto_increment,
  `id_num` varchar(20) NOT NULL,
  `staff_name` varchar(10) NOT NULL,
  `login_ip` varchar(15) NOT NULL,
  `staff_action` varchar(10) NOT NULL,
  `action_time` varchar(25) NOT NULL,
  `record_viewed` varchar(11) default NULL,
  `spare1` varchar(20) default NULL,
  `spare2` varchar(20) default NULL,
  PRIMARY KEY  (`log_id`)
) ENGINE=InnoDB AUTO_INCREMENT=356276 DEFAULT CHARSET=utf8


//记录商企工资单具体数据
CREATE TABLE `biz_data_salary` (
  `sid` int(11) NOT NULL auto_increment,
  `MONTH` varchar(6) NOT NULL,
  `ID_NUM` varchar(20) NOT NULL,
  `TIME` varchar(15) NOT NULL,
  `DEPARTMENT` varchar(20) NOT NULL,
  `STAFF_NAME` varchar(10) NOT NULL,
  `TITLE` varchar(10) NOT NULL,
  `expend1` varchar(12) default NULL,
  `expend2` varchar(12) default NULL,
  `expend3` varchar(12) default NULL,
  `expend4` varchar(12) default NULL,
  `expend5` varchar(12) default NULL,
  `expend6` varchar(12) default NULL,
  `expend7` varchar(12) default NULL,
  `expend8` varchar(12) default NULL,
  `expend9` varchar(12) default NULL,
  `expend10` varchar(12) default NULL,
  `middle1` varchar(12) default NULL,
  `middle2` varchar(12) default NULL,
  `middle3` varchar(12) default NULL,
  `middle4` varchar(12) default NULL,
  `middle5` varchar(12) default NULL,
  `middle6` varchar(12) default NULL,
  `middle7` varchar(12) default NULL,
  `middle8` varchar(12) default NULL,
  `item_value1` varchar(12) default NULL,
  `item_value2` varchar(12) default NULL,
  `item_value3` varchar(12) default NULL,
  `item_value4` varchar(12) default NULL,
  `item_value5` varchar(12) default NULL,
  `item_value6` varchar(12) default NULL,
  `item_value7` varchar(12) default NULL,
  `item_value8` varchar(12) default NULL,
  `item_value9` varchar(12) default NULL,
  `item_value10` varchar(12) default NULL,
  `item_value11` varchar(12) default NULL,
  `item_value12` varchar(12) default NULL,
  `item_value13` varchar(12) default NULL,
  `item_value14` varchar(12) default NULL,
  `item_value15` varchar(12) default NULL,
  `item_value16` varchar(12) default NULL,
  `item_value17` varchar(12) default NULL,
  `item_value18` varchar(12) default NULL,
  `item_value19` varchar(12) default NULL,
  `item_value20` varchar(12) default NULL,
  `item_value21` varchar(12) default NULL,
  `item_value22` varchar(12) default NULL,
  `item_value23` varchar(12) default NULL,
  `item_value24` varchar(12) default NULL,
  `item_value25` varchar(12) default NULL,
  `item_value26` varchar(12) default NULL,
  `item_value27` varchar(12) default NULL,
  `item_value28` varchar(12) default NULL,
  `item_value29` varchar(12) default NULL,
  `item_value30` varchar(12) default NULL,
  `item_value31` varchar(12) default NULL,
  `item_value32` varchar(12) default NULL,
  `item_value33` varchar(12) default NULL,
  `item_value34` varchar(12) default NULL,
  `item_value35` varchar(12) default NULL,
  `item_value36` varchar(12) default NULL,
  `item_value37` varchar(12) default NULL,
  `item_value38` varchar(12) default NULL,
  `TOTAL_RECV` varchar(12) default NULL,
  `INSURE_COM` varchar(12) default NULL,
  `INSURE_SELF` varchar(12) default NULL,
  `HOUSE_FUND_COM` varchar(12) default NULL,
  `HOUSE_FUND_SELF` varchar(12) default NULL,
  `bottom1` varchar(12) default NULL,
  `bottom2` varchar(12) default NULL,
  `bottom3` varchar(12) default NULL,
  `bottom4` varchar(12) default NULL,
  `bottom5` varchar(12) default NULL,
  `bottom6` varchar(12) default NULL,
  `bottom7` varchar(12) default NULL,
  `bottom8` varchar(12) default NULL,
  `bottom9` varchar(12) default NULL,
  `bottom10` varchar(50) default NULL,
  PRIMARY KEY  (`sid`)
) ENGINE=InnoDB AUTO_INCREMENT=5585 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT

//记录商企工资单表头结构
CREATE TABLE `biz_template` (
  `bid` int(11) NOT NULL auto_increment,
  `month` varchar(6) NOT NULL,
  `param` varchar(20) NOT NULL,
  `value` varchar(50) NOT NULL,
  `valid_tag` tinyint(1) default NULL,
  `remark` varchar(10) default NULL,
  `spare1` varchar(20) default NULL,
  `spare2` varchar(20) default NULL,
  PRIMARY KEY  (`bid`)
) ENGINE=InnoDB AUTO_INCREMENT=2275 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT





